name: Auto Backup
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto backup"
          git push git@github.com:prakash8soni/wisdom.git main